function obj = pop_eegbrowser(EEG, icacomp)
if nargin < 2, icacomp = 1;end
if icacomp==0 && ~isempty(EEG.icaact)
    EEG_ica = EEG;
    EEG_ica.data = EEG_ica.icaact;
    EEG_ica.icaact = [];
    EEG_ica.icacomp = [];
    EEG_ica.icasphere = [];
    EEG_ica.icasplinefile = [];
    EEG_ica.icaweights = [];
    EEG_ica.icawinv = [];
    EEG_ica.nbchan = size(EEG_ica.data,1);
    EEG_ica.chanlocs = struct('labels',[],'X',[],'Y',[],'Z',[],'ref',[],'theta',[],'radius',[],'sph_theta',[],'sph_phi',[],'sph_radius',[],'type', 'EEG','urchan',[]);    
    for ic=1:EEG_ica.nbchan
        EEG_ica.chanlocs(ic) = struct('labels',['IC' num2str(ic)],...
            'X',[],...
            'Y',[],...
            'Z',[],...
            'ref','', ...
            'theta',[], ...
            'radius',[], ...
            'sph_theta', [], ...
            'sph_phi',[], ...
            'sph_radius',[], ...
            'type', 'EEG', ...
            'urchan', []);
    end
    EEG = EEG_ica;
end
obj = EEGBrowser(EEG);